export const enemiesData = {
    enemy1: {
      name: "Mr. Krabs",
      type: "basic",
      maxHp: 100, //LOCKED
      speed: 0.56, //LOCKED
      reward: 1,
      image: "assets/enemies/enemy1.png",
      isFlying: false,
      sizeMultiplier: 0.55,
    },
    enemy2: {
      name: "Shpider",
      type: "basic",
      maxHp: 120, //LOCKED
      speed: 0.37, //LOCKED
      reward: 1,
      image: "assets/enemies/enemy2.png",
      isFlying: false,
      sizeMultiplier: 0.55,
    },
    enemy3: {
        name: "Robot Shpider",
        type: "basic",
        maxHp: 140, 
        speed: 0.6, 
        reward: 1,
        image: "assets/enemies/enemy3.png",
        isFlying: false,
        sizeMultiplier: 0.55,
    },
    enemy4: {
        name: "Krustacean",
        type: "basic",
        maxHp: 175, 
        speed: 0.7, 
        reward: 1,
        image: "assets/enemies/enemy4.png",
        isFlying: false,
        sizeMultiplier: 0.55,
    },
    enemy5: {
        name: "Vagrant Dead",
        type: "basic",
        maxHp: 205, 
        speed: 0.7, 
        reward: 1,
        image: "assets/enemies/enemy5.png",
        isFlying: false,
        sizeMultiplier: 0.7,
    },
    enemy6: {
      name: "Charles Barkley Dead",
      type: "basic",
      maxHp: 250, 
      speed: 0.71, 
      reward: 1,
      image: "assets/enemies/enemy6.png",
      isFlying: false,
      sizeMultiplier: 0.65,
    },
    enemy7: {
      name: "El Diablin",
      type: "basic",
      maxHp: 290, 
      speed: 0.73, 
      reward: 2,
      image: "assets/enemies/enemy7.png",
      isFlying: false,
      sizeMultiplier: 0.65,
    },
    enemy8: {
      name: "Mini-Van Falcon",
      type: "speed",
      maxHp: 250, 
      speed: 1.43, 
      reward: 2,
      image: "assets/enemies/enemy8.png",
      isFlying: false,
      sizeMultiplier: 0.7,
    },
    enemy9: {
      name: "Lil Chickn-Hed",
      type: "bonus",
      maxHp: 770, 
      speed: 0.91,
      reward: 9,
      image: "assets/enemies/enemy9.png",
      isFlying: false,
      sizeMultiplier: 0.6,
    },
    enemy10: {
      name: "Russell ScareCrowe",
      type: "boss",
      maxHp: 3000, 
      speed: 0.78,
      reward: 1,
      lifeReward: 1,
      image: "assets/enemies/enemy10.png",
      isFlying: false,
      sizeMultiplier: 1.3,
    },

  };
  